apiVersion: v1
kind: Service
metadata:
  name: {{ include "govai.fullname" . }}-api
  labels:
    {{- include "govai.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
  selector:
    {{- include "govai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
